// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Prefer the standard Supabase env var name, but keep compatibility with the repo’s custom one.
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

// In demo mode (or on hosts where env vars aren't configured yet), don't hard-crash the app.
// We'll still create a client with harmless placeholders; any DB/auth calls will simply fail,
// but the UI can render using mock/simulated data.
const RESOLVED_SUPABASE_URL = SUPABASE_URL || "https://placeholder.supabase.co";
const RESOLVED_SUPABASE_KEY = SUPABASE_PUBLISHABLE_KEY || "placeholder-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(RESOLVED_SUPABASE_URL, RESOLVED_SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});